# Home directory 
my_home: "{{ lookup('env', 'HOME') }}"

# SSH
ssh_dest_dir: "{{ lookup('env', 'HOME') }}/.ssh"
ssh_files: 
  - id_rsa
ssh_known_hosts: 
  - github.com
ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"

# Golang
golang_install: true
golang_version: "1.20.5"

# Neovim 
nvim_version: "0.9.1"
nvim_install_dest: "/usr/local"

# Docker
docker_compose_version: "2.6.1"

# NodeJS
node_nvm_version: "0.39.1"
node_versions: 
  - 18.4.0
  - 16.15.1

node_global_packages:
  - yarn
  - yo
  - typescript
  - ts-node
  - nodemon
  - eslint

tmux_version: "3.3a"

# gcloud 
gcloud_extras:
  - kubectl
  - google-cloud-sdk-gke-gcloud-auth-plugin

