- hosts: localhost
  vars: 
    my_home: "{{ lookup('env', 'HOME') }}"

    # golang
    golang_version: "1.18.3"

    # neovim 
    nvim_version: "0.7.2"
    nvim_install_dest: "/usr/local"

    # NodeJS
    node_nvm_version: "0.39.1"
    node_versions: 
      - 18.4.0
      - 16.15.1

  pre_tasks:
    - name: Update APT
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/neovim-setup.yml
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/go-setup.yml

