- hosts: localhost
  vars_files:
    - config.default.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Update APT
      become: true
      apt:
        update_cache: true
        upgrade: dist
      tags: ['always']

  tasks:
    - import_tasks: tasks/core-setup.yml
    # - import_tasks: tasks/nix_install.yml
    # - import_tasks: tasks/nix_packages.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/ssh-setup.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/tmux-setup.yml
    # - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/neovim-setup.yml
    - import_tasks: tasks/go-setup.yml
    - import_tasks: tasks/go-packages.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/rust-setup.yml
    - import_tasks: tasks/alacritty.yml
    - import_tasks: tasks/gcloud-setup.yml
    - import_tasks: tasks/awscli-setup.yml
    - import_tasks: tasks/docker-setup.yml
#    - import_tasks: tasks/hashicorp-setup.yml
#   - import_tasks: tasks/pulumi-setup.yml
