- name: Setup Go
  tags:
    - install
    - go
  block:
    - name: Check current golang version
      command: bash -c "/usr/local/go/bin/go version|sed -e 's/go version go//g'|cut -d' ' -f1"
      ignore_errors: yes
      register: current_golang_version
      changed_when: false

    - debug: msg="current_golang_version={{ current_golang_version.stdout }}"
    - debug: msg="golang_version={{ golang_version }}"

    - name: Continue only when version is older
      fail: msg="Version already exists"
      when: current_golang_version.stdout != "" and current_golang_version.stdout is version(golang_version, operator='ge', strict=True)

    - debug: msg="Continuing with installation"

    - name: Remove old installation of Go
      file:
        path: /usr/local/go
        state: absent
      become: yes

    - name: "Download Go {{ golang_version }}"
      unarchive:
        src: "https://storage.googleapis.com/golang/go{{ golang_version }}.linux-amd64.tar.gz"
        dest: "/usr/local"
        remote_src: yes
      become: true

