- name: hashicorp setup
  tags: 
    - install
    - terraform 
    - hashicorp
  become: true
  block:
    - name: Import public key for hashicorp
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp.gpg

    - name: Add the official HashiCorp Linux repository
      shell: >
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
              tee -a /etc/apt/sources.list.d/hashicorp.list
      args:
        executable: /bin/bash
        creates: /etc/apt/sources.list.d/hashicorp.list

    - name: Update APT
      apt:
        force_apt_get: true
        update_cache: true
        state: present

    - name: Install hashicorp packages
      apt: 
        name: "{{ item }}"
        state: latest
      loop: 
        - terraform
        - vault

