- name: Install NPM packages
  tags:
    - install
    - node

  block: 
    - name: Get NodeJs version
      command: bash -c "source {{ my_home }}/.nvm/nvm.sh && nvm current"
      ignore_errors: true
      register: current_node

    - name: Install global NPM packages
      npm:
        name: "{{ item }}"
        global: true
      loop: "{{ npm_packages }}"
      environment:
        PATH: "{{ my_home }}/.nvm/versions/node/{{ current_node.stdout }}/bin:{{ ansible_env.PATH }}"

