- name: Setup Rust
  tags: 
    - install
    - rust

  block:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: true

    - name: install Rust
      shell: >
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      when: cargo_exists is failed

